# ===============================
# = Hibernate datasource
# ===============================
spring:
  datasource:
    url: jdbc:mysql://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:3306/XXXXXX?serverTimezone=UTC
#    url: jdbc:mysql://localhost:3306/db_eduini?serverTimezone=UTC
    username: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    password: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#    password: root
  devtools:
    restart:
      additional-paths: /git/sysadap/src/main/resources/templates

# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: true
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: update
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

# ===============================
# = MAIL configurations
# ===============================
  mail:
    default-encoding: UTF-8
    host: email-smtp.us-east-1.amazonaws.com
    username: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    password: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    port: 587
    #host: mailrelay.intranet.hdp.be
    #username: test
    #password: test
    #port:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

# ===============================
# = Logging configurations
# ===============================
logging:
  level:
    root: WARN
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    
  
accessKey:
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
secretKey:
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
region:
  us-east-1
  
accountSid:
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
authToken:
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  
urlCntx:
  http://localhost:8080
  