# ===============================
# = Hibernate datasource
# ===============================
spring:
  datasource:
#    url: jdbc:mysql://dbeduini2.c6qojqnu4td3.us-east-1.rds.amazonaws.com:3306/db_eduini?serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/db_eduini?serverTimezone=UTC
    username: root
#    password: adminHola1414
    password: root
  devtools:
    restart:
      additional-paths: /Users/Oscar/git/sysadap/sysadap/src/main/resources/templates

# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: true
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: update
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

# ===============================
# = MAIL configurations
# ===============================
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: sysadapini@gmail.com
    password: Hola1414
    port: 587
    #host: mailrelay.intranet.hdp.be
    #username: test
    #password: test
    #port:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

# ===============================
# = Logging configurations
# ===============================
logging:
  level:
    root: WARN
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    
#server:
#  port: 8080
  