# ===============================
# = Hibernate datasource
# ===============================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_eduini?serverTimezone=UTC
    username: root
    password: root
  devtools:
    restart:
      additional-paths: /Users/Oscar/git/reset-password/src/main/resources/templates

# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: true
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: update
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

# ===============================
# = MAIL configurations
# ===============================
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: alquilerautosrara@gmail.com
    password: alquilerautosrara123
    port: 587
    #host: mailrelay.intranet.hdp.be
    #username: test
    #password: test
    #port:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

# ===============================
# = Logging configurations
# ===============================
logging:
  level:
    root: WARN
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    
#server:
#  port: 9000
  